api/urls.py
from django.urls import path
from . import views

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>', views.getProject),
    ]

gscteam/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
    path('', include('users.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'),
         name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'),
         name="password_reset_done"),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'),
         name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'),
         name="password_reset_complete"),

      
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from projects.views import create_project
from . import views

urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('logout/', views.logout_user, name="logout"),
    path('register/', views.register_user, name="register"),

    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>', views.profile, name="profile"),
    path('account/', views.account, name="account"),
    path('profile_form/', views.edit_account, name='edit_account'),
    
    path('skill_form/', views.create_skill, name='create_skill'),
    path('update_skill/<str:pk>', views.update_skill, name='update_skill'),
    path('delete_skill/<str:pk>', views.delete_skill, name="delete_skill"),

    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>', views.view_message, name="message"),
    path('create_message/<str:pk>', views.create_message, name="create_message"),
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

# Create your models here.
class Project(models.Model):
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    

    def __str__(self):
        return f"{self.title}"
    class Meta:
        ordering=['-vote_ratio', '-vote_total', '-title']

    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset

    @property
    def getVoteCount(self):
        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()
        ratio = (upVotes/totalVotes)*100
        self.vote_ratio = ratio
        self.vote_total = totalVotes
        self.save()
    

class Review(models.Model):
    VOTE_TYPE =( 
        ('up','Up Vote'),
        ('down', 'Down Vote'),
    )
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(blank=True,null=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)    

    class Meta:
        unique_together = [['owner', 'project']]
        
    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False) 

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to="profiles/", default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def __str__(self):
        return str(self.user.username)

    class Meta:
        ordering=['created']

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    
    
    def __str__(self):
        return str(self.name )


class Message(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True, blank=True, related_name="messages")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
    

users/forms.py
from django.forms import ModelForm, fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from .models import Message, Profile, Skill


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',

        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
    
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'email', 'username', 'location', 'bio', 'short_intro', 'profile_image',
                'social_github', 'social_linkedin', 'social_twitter', 'social_website']

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
    
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

class SkillForm(ModelForm):
    class Meta:
        model = Skill
        fields = '__all__'
        exclude = ['owner']

    def __init__(self, *args, **kwargs):
        super(SkillForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['name', 'email', 'subject', 'body'] 

    def __init__(self, *args, **kwargs):
        super(MessageForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect 
from .models import Profile, Message
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm, ProfileForm, SkillForm, MessageForm
from .utils import pagination_profiles, search_profiles
# Create your views here.


def login_page(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')
        
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')
        else:
            messages.error(request, 'Username or password incorrect!')
    context = {'page': page,}
    return render(request, 'users/login_register.html', context )

def logout_user(request):
    logout(request)
    messages.info(request, 'User sucessfull logout!')
    return redirect('login')

def register_user(request):
    page = 'register'
    form = CustomUserCreationForm()
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, 'User account created sucessfully!')
            login(request, user)
            return redirect('edit_account')
        else:
            messages.error(request, 'And error has ocurred during registration!')
    context={'page': page, 'form':form}
    return render(request, 'users/login_register.html', context)


def profiles(request):
    profiles, search_query = search_profiles(request)
    custom_range, profiles = pagination_profiles(request, profiles, 6)
    context ={
        'profiles':profiles,'search_query':search_query,
        'custom_range':custom_range,
    }
    return render(request, 'users/profiles.html', context)


def profile(request, pk):
    profile = Profile.objects.get(id=pk)
    
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description__exact="")

    context = {
        'top_skills':top_skills,
        'profile':profile,
        'other_skills':other_skills,
        
    }
    return render(request, 'users/profile.html', context)

@login_required(login_url='login')
def account(request):
    profile = request.user.profile
    skills = profile.skill_set.all()
    context = { 'profile': profile, 'skills': skills, }
    return render(request, 'users/account.html', context)

def edit_account(request):
    profile = request.user.profile
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'User account Updated sucessfully!')
            return redirect('account')
    context={'form':form}
    return render(request, 'users/profile_form.html', context)

@login_required(login_url='login')
def create_skill(request):
    profile = request.user.profile
    form = SkillForm()
    if request.method == 'POST':
        form = SkillForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = profile
            skill.save()
            messages.success(request, 'Skill added sucessfully!')
            return redirect('account')
    context={'form':form}
    return render(request, 'users/skill_form.html', context)

@login_required(login_url='login')
def update_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    form = SkillForm(instance=skill)

    if request.method == 'POST':
        form = SkillForm(request.POST, instance=skill)
        if form.is_valid():       
            form.save()
            messages.success(request, 'Skill Updated sucessfully!')
            return redirect('account')
    context={'form':form}
    return render(request, 'users/skill_form.html', context)

@login_required(login_url='login')
def delete_skill(request, pk):
    profile = request.user.profile
    skill = profile.skill_set.get(id=pk)
    if request.method == 'POST':
        skill.delete()
        messages.success(request, 'Skill Removed sucessfully!')
        return redirect('account')
    context={'object':skill}
    return render(request, 'delete_template.html', context)

@login_required(login_url='login')
def inbox(request):
    #A (user) -> B (profile)
    profile = request.user.profile
    #B (profile) -> C (messages)
    messageRequests = profile.messages.all()
    # Where read = False
    unreadCount = messageRequests.filter(is_read=False).count()
    context={ 'messageRequests': messageRequests, 'unreadCount':unreadCount}
    return render(request, 'users/inbox.html', context)

@login_required(login_url='login')
def view_message(request, pk):
    profile = request.user.profile
    message = profile.messages.get(id=pk)
    if message.is_read == False:
        message.is_read = True
        message.save()
    context = {'message':message}
    return render(request, 'users/message.html', context)

def create_message(request, pk):
    recipient = Profile.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profile
    except:
        sender = None
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():  
            message = form.save(commit=False)     
            message.sender = sender
            message.recipient = recipient
            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()
            messages.success(request, 'Your message was sucessfully sent!')
            return redirect('profile', recipient.id)
    context = { 'recipient':recipient, 'form':form }
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit_account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.based}}, Portugal</p>
              <ul class="dev__social">
                {% if profile.social_github%}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {%endif%}
                {% if profile.social_twitter %}
                <li>
                  <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {%endif%}
                {% if profile.social_linkedin%}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {%endif%}
                {% if profile.social_website%}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {%endif%}
              </ul>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
             {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create_skill' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">
           {% for skill in skills %}
            <tr>
              <td class="settings__tableInfo">
                <h4>{{skill.name}}</h4>
                <p>
                  {{skill.description}}
                </p>
              </td>
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update_skill' skill.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_skill' skill.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr>
            {% endfor %}
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">
            {% for project in profile.project_set.all %}
            <tr>
              <td class="settings__thumbnail">
                <a href="{% url 'project' project.id%}"><img src="{{project.featured_image.url}}" alt="Project Thumbnail" /></a>
              </td>
              <td class="settings__tableInfo">
                <a href="{% url 'project' project.id%}">{{project.title}}</a>
                <p>
                  {{project.description|slice:"200"}}
                </p>
              </td>
              {% if project.owner %}
              <td class="settings__tableActions">
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
                <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete_template' project.id %}?next=/account"><i class="im im-x-mark-circle-o"></i>
                  Delete</a>
              </td>
            </tr> 
            {% endif %}
            {% endfor %}

           
            
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock content %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}


  <!-- Main Section -->
  <main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        {% for message in messageRequests %}
        {% if message.is_read == False %}
        <li class="message message--unread">
        {% else %}
        <li class="message">
        {% endif %}
          <a href="{%url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}
      </ul>
    </div>
{% endblock content%}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% if page == 'register' %}
<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/gsc_color.svg' %}" alt="icon" />
        </a>
        <h4>Account</h4>
        <p>Create a new account</p>
      </div>

      <form method="POST" action="{% url 'register' %}" class="form auth__form">
        {% csrf_token %} 

        {% for field in form %}
        <div class="form__field">
          <label for="formInput#text">{{field.label}}</label>
          {{field}} 

          {% for error in field.errors %}
            <small style="color: red;">{{error}}</small>
          {% endfor %}
        </div>
        {% endfor %}
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Register User" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login' %}">Log In</a>
      </div>
    </div>
  </div>


{% else %}
<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/gsc_color.svg' %}" alt="icon" />
        </a>
        <h4>Account Login</h4>
        <p>Hello, Welcome Back!</p>
      </div>
      <form action="" method="POST" class="form auth__form">
        {% csrf_token %}
        <!-- Input:Email -->
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>
        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="Enter your password..."
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" name="login" />
          <a href="{% url 'reset_password' %}">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register' %}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}

{% endblock content %}

users/templates/users/message.html
{% extends 'main.html' %}

{% block content %}
  <!-- Main Section -->
  <main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox' %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{message.subject}}</h4>
          <a href="profile.html" class="message__author">{{message.name}}</a>
          <p class="message__date">{{message.created}}</p>
          <div class="message__body">
            {{message.body|linebreaksbr}}
          </div>
      </div>
    </div>
    {% endblock content %}

users/templates/users/message_form.html
{% extends 'main.html' %}

{% block content %}
    <!-- Main Section -->
    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'profile' recipient.id %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" method="POST">
                    {% csrf_token %}

                    {% if request.user.is_authenticated == False %}
                    <div class="form__field">
                        <label for="formInput#text">{{form.name.label}}</label>
                        {{form.name}}
                    </div>
                    <div class="form__field">
                        <label for="formInput#text">{{form.email.label}}</label>
                        {{form.email}}
                    </div>
                    {% endif %}
                    <div class="form__field">
                        <label for="formInput#text">{{form.subject.label}}</label>
                        {{form.subject}}
                    </div>
                    <div class="form__field">
                        <label for="formInput#text">{{form.body.label}}</label>
                        {{form.body}}
                    </div>


                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main.html' %}

{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{ profile.profile_image.url }}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}, Portugal</p>
              <ul class="dev__social">
                {% if profile.social_github%}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {%endif%}
                {% if profile.social_twitter%}
                <li>
                  <a title="Twitter" href="{{ profile.social_twitter }}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {%endif%}
                {% if profile.social_linkedin%}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {%endif%}
                {% if profile.social_website%}
                <li>
                  <a title="Personal Website" href="{{ profile.social_website }}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {%endif%}
              </ul>
              {% if request.user.profile.id != profile.id %}
              <a href="{% url 'create_message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              {% endif %}
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
                {% for skill in top_skills %}
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">                
                  {{skill.description}}
                </p>
              </div>
              {% endfor %}
              
              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">                 
                  <small>{{skill}}</small>
                </span>
                {% endfor %}
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">
                {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{ project.featured_image.url }}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="#">By {{ project.owner }}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{ project.vote_total }} Vote{{project.vote_total|pluralize:"s"}})
                      </p>
                      <div class="project__tags">
                     {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                    {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
         
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock content %}

users/templates/users/profile_form.html
{% extends 'main.html'%}

{% block content %}

<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>
            <h4>Profile</h4>
            <form class="form" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                {% for field in form %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}

                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>

{% endblock content %}